package globuswoo.entity;
// Generated May 23, 2013 8:20:10 PM by Hibernate Tools 3.2.1.GA


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Payments generated by hbm2java
 */
@Entity
@Table(name="payments")
public class Payments  implements java.io.Serializable {


     private Integer paymentId;
     private Customers customers;
     private Plans plans;
     private Integer resellerId;
     private float amount;
     private Date beginDate;
     private Date endDate;
     private Date paymentDate;
     private String payerId;
     private String ebayTransactionId;

    public Payments() {
    }

	
    public Payments(Customers customers, float amount, Date beginDate, Date endDate, Date paymentDate, String payerId, String ebayTransactionId) {
        this.customers = customers;
        this.amount = amount;
        this.beginDate = beginDate;
        this.endDate = endDate;
        this.paymentDate = paymentDate;
        this.payerId = payerId;
        this.ebayTransactionId = ebayTransactionId;
    }
    public Payments(Customers customers, Plans plans, Integer resellerId, float amount, Date beginDate, Date endDate, Date paymentDate, String payerId, String ebayTransactionId) {
       this.customers = customers;
       this.plans = plans;
       this.resellerId = resellerId;
       this.amount = amount;
       this.beginDate = beginDate;
       this.endDate = endDate;
       this.paymentDate = paymentDate;
       this.payerId = payerId;
       this.ebayTransactionId = ebayTransactionId;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)
    
    @Column(name="PaymentID", unique=true, nullable=false)
    public Integer getPaymentId() {
        return this.paymentId;
    }
    
    public void setPaymentId(Integer paymentId) {
        this.paymentId = paymentId;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="CustomerID", nullable=false)
    public Customers getCustomers() {
        return this.customers;
    }
    
    public void setCustomers(Customers customers) {
        this.customers = customers;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="PlanID")
    public Plans getPlans() {
        return this.plans;
    }
    
    public void setPlans(Plans plans) {
        this.plans = plans;
    }
    
    @Column(name="ResellerId")
    public Integer getResellerId() {
        return this.resellerId;
    }
    
    public void setResellerId(Integer resellerId) {
        this.resellerId = resellerId;
    }
    
    @Column(name="Amount", nullable=false, precision=11, scale=0)
    public float getAmount() {
        return this.amount;
    }
    
    public void setAmount(float amount) {
        this.amount = amount;
    }
    @Temporal(TemporalType.DATE)
    @Column(name="BeginDate", nullable=false, length=0)
    public Date getBeginDate() {
        return this.beginDate;
    }
    
    public void setBeginDate(Date beginDate) {
        this.beginDate = beginDate;
    }
    @Temporal(TemporalType.DATE)
    @Column(name="EndDate", nullable=false, length=0)
    public Date getEndDate() {
        return this.endDate;
    }
    
    public void setEndDate(Date endDate) {
        this.endDate = endDate;
    }
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="PaymentDate", nullable=false, length=0)
    public Date getPaymentDate() {
        return this.paymentDate;
    }
    
    public void setPaymentDate(Date paymentDate) {
        this.paymentDate = paymentDate;
    }
    
    @Column(name="PayerID", nullable=false, length=50)
    public String getPayerId() {
        return this.payerId;
    }
    
    public void setPayerId(String payerId) {
        this.payerId = payerId;
    }
    
    @Column(name="EbayTransactionID", nullable=false, length=50)
    public String getEbayTransactionId() {
        return this.ebayTransactionId;
    }
    
    public void setEbayTransactionId(String ebayTransactionId) {
        this.ebayTransactionId = ebayTransactionId;
    }




}


