package globuswoo.entity;
// Generated May 23, 2013 8:20:10 PM by Hibernate Tools 3.2.1.GA


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Reseller generated by hbm2java
 */
@Entity
@Table(name="reseller")
public class Reseller  implements java.io.Serializable {


     private Long resellerId;
     private long paymentId;
     private String firstName;
     private String lastName;
     private String phone;
     private String address;
     private String city;
     private String state;
     private String country;
     private int zipCode;
     private int allowedUserCount;
     private int activeUserCount;
     private int allowedCampaignsCount;
     private int activeCampaignsCount;
     private int allowedKeywordCount;
     private int activeKeywordCount;
     private String timezoneId;
     private String timezoneValue;
     private String alertEmailId;
     private String alertNotificationCount;
     private String companyUrllink;
     private String companyLogoLink;
     private String companyDescription;

    public Reseller() {
    }

    public Reseller(long paymentId, String firstName, String lastName, String phone, String address, String city, String state, String country, int zipCode, int allowedUserCount, int activeUserCount, int allowedCampaignsCount, int activeCampaignsCount, int allowedKeywordCount, int activeKeywordCount, String timezoneId, String timezoneValue, String alertEmailId, String alertNotificationCount, String companyUrllink, String companyLogoLink, String companyDescription) {
       this.paymentId = paymentId;
       this.firstName = firstName;
       this.lastName = lastName;
       this.phone = phone;
       this.address = address;
       this.city = city;
       this.state = state;
       this.country = country;
       this.zipCode = zipCode;
       this.allowedUserCount = allowedUserCount;
       this.activeUserCount = activeUserCount;
       this.allowedCampaignsCount = allowedCampaignsCount;
       this.activeCampaignsCount = activeCampaignsCount;
       this.allowedKeywordCount = allowedKeywordCount;
       this.activeKeywordCount = activeKeywordCount;
       this.timezoneId = timezoneId;
       this.timezoneValue = timezoneValue;
       this.alertEmailId = alertEmailId;
       this.alertNotificationCount = alertNotificationCount;
       this.companyUrllink = companyUrllink;
       this.companyLogoLink = companyLogoLink;
       this.companyDescription = companyDescription;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)
    
    @Column(name="ResellerId", unique=true, nullable=false)
    public Long getResellerId() {
        return this.resellerId;
    }
    
    public void setResellerId(Long resellerId) {
        this.resellerId = resellerId;
    }
    
    @Column(name="PaymentID", nullable=false)
    public long getPaymentId() {
        return this.paymentId;
    }
    
    public void setPaymentId(long paymentId) {
        this.paymentId = paymentId;
    }
    
    @Column(name="FirstName", nullable=false, length=20)
    public String getFirstName() {
        return this.firstName;
    }
    
    public void setFirstName(String firstName) {
        this.firstName = firstName;
    }
    
    @Column(name="LastName", nullable=false, length=30)
    public String getLastName() {
        return this.lastName;
    }
    
    public void setLastName(String lastName) {
        this.lastName = lastName;
    }
    
    @Column(name="Phone", nullable=false, length=30)
    public String getPhone() {
        return this.phone;
    }
    
    public void setPhone(String phone) {
        this.phone = phone;
    }
    
    @Column(name="Address", nullable=false, length=50)
    public String getAddress() {
        return this.address;
    }
    
    public void setAddress(String address) {
        this.address = address;
    }
    
    @Column(name="City", nullable=false, length=20)
    public String getCity() {
        return this.city;
    }
    
    public void setCity(String city) {
        this.city = city;
    }
    
    @Column(name="State", nullable=false, length=20)
    public String getState() {
        return this.state;
    }
    
    public void setState(String state) {
        this.state = state;
    }
    
    @Column(name="Country", nullable=false, length=20)
    public String getCountry() {
        return this.country;
    }
    
    public void setCountry(String country) {
        this.country = country;
    }
    
    @Column(name="ZipCode", nullable=false)
    public int getZipCode() {
        return this.zipCode;
    }
    
    public void setZipCode(int zipCode) {
        this.zipCode = zipCode;
    }
    
    @Column(name="AllowedUserCount", nullable=false)
    public int getAllowedUserCount() {
        return this.allowedUserCount;
    }
    
    public void setAllowedUserCount(int allowedUserCount) {
        this.allowedUserCount = allowedUserCount;
    }
    
    @Column(name="ActiveUserCount", nullable=false)
    public int getActiveUserCount() {
        return this.activeUserCount;
    }
    
    public void setActiveUserCount(int activeUserCount) {
        this.activeUserCount = activeUserCount;
    }
    
    @Column(name="AllowedCampaignsCount", nullable=false)
    public int getAllowedCampaignsCount() {
        return this.allowedCampaignsCount;
    }
    
    public void setAllowedCampaignsCount(int allowedCampaignsCount) {
        this.allowedCampaignsCount = allowedCampaignsCount;
    }
    
    @Column(name="ActiveCampaignsCount", nullable=false)
    public int getActiveCampaignsCount() {
        return this.activeCampaignsCount;
    }
    
    public void setActiveCampaignsCount(int activeCampaignsCount) {
        this.activeCampaignsCount = activeCampaignsCount;
    }
    
    @Column(name="AllowedKeywordCount", nullable=false)
    public int getAllowedKeywordCount() {
        return this.allowedKeywordCount;
    }
    
    public void setAllowedKeywordCount(int allowedKeywordCount) {
        this.allowedKeywordCount = allowedKeywordCount;
    }
    
    @Column(name="ActiveKeywordCount", nullable=false)
    public int getActiveKeywordCount() {
        return this.activeKeywordCount;
    }
    
    public void setActiveKeywordCount(int activeKeywordCount) {
        this.activeKeywordCount = activeKeywordCount;
    }
    
    @Column(name="TimezoneID", nullable=false, length=50)
    public String getTimezoneId() {
        return this.timezoneId;
    }
    
    public void setTimezoneId(String timezoneId) {
        this.timezoneId = timezoneId;
    }
    
    @Column(name="TimezoneValue", nullable=false, length=50)
    public String getTimezoneValue() {
        return this.timezoneValue;
    }
    
    public void setTimezoneValue(String timezoneValue) {
        this.timezoneValue = timezoneValue;
    }
    
    @Column(name="AlertEmailID", nullable=false, length=50)
    public String getAlertEmailId() {
        return this.alertEmailId;
    }
    
    public void setAlertEmailId(String alertEmailId) {
        this.alertEmailId = alertEmailId;
    }
    
    @Column(name="AlertNotificationCount", nullable=false, length=50)
    public String getAlertNotificationCount() {
        return this.alertNotificationCount;
    }
    
    public void setAlertNotificationCount(String alertNotificationCount) {
        this.alertNotificationCount = alertNotificationCount;
    }
    
    @Column(name="CompanyURLLink", nullable=false, length=200)
    public String getCompanyUrllink() {
        return this.companyUrllink;
    }
    
    public void setCompanyUrllink(String companyUrllink) {
        this.companyUrllink = companyUrllink;
    }
    
    @Column(name="CompanyLogoLink", nullable=false, length=200)
    public String getCompanyLogoLink() {
        return this.companyLogoLink;
    }
    
    public void setCompanyLogoLink(String companyLogoLink) {
        this.companyLogoLink = companyLogoLink;
    }
    
    @Column(name="CompanyDescription", nullable=false, length=200)
    public String getCompanyDescription() {
        return this.companyDescription;
    }
    
    public void setCompanyDescription(String companyDescription) {
        this.companyDescription = companyDescription;
    }




}


