package globuswoo.entity;
// Generated May 23, 2013 8:20:10 PM by Hibernate Tools 3.2.1.GA

import java.util.Collection;
import java.util.Date;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.xml.bind.annotation.XmlTransient;

/**
 * Alertsdata generated by hbm2java
 */
@Entity
@Table(name = "alertsdata")
public class Alertsdata implements java.io.Serializable {
    @OneToMany(cascade = CascadeType.ALL, mappedBy = "customerId")
    private Collection<Reviewsite> reviewsiteCollection;

    @JoinColumn(name = "CustomerID", referencedColumnName = "CustomerID")
    @ManyToOne(optional = false)
    private Customers customerID;
    @Id
    @GeneratedValue(strategy = IDENTITY)
    @Column(name = "AlertID", unique = true, nullable = false)
    private Integer alertId;
    @Column(name = "ResellerId")
    private Integer resellerId;
    @Column(name = "Campaign", nullable = false, length = 50)
    private String campaign;
    @Column(name = "Url", nullable = false, length = 300)
    private String url;
    @Column(name = "Keyword", nullable = false, length = 50)
    private String keyword;
    @Column(name = "Engine", nullable = false, length = 10)
    private String engine;
    @Column(name = "PreviousRank", nullable = false)
    private int previousRank;
    @Column(name = "CurrentRank", nullable = false)
    private int currentRank;
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "TrackDate", nullable = false, length = 0)
    private Date trackDate;

    public Alertsdata() {
    }

    public Alertsdata(String campaign, String url, String keyword, String engine, int previousRank, int currentRank, Date trackDate) {
        this.campaign = campaign;
        this.url = url;
        this.keyword = keyword;
        this.engine = engine;
        this.previousRank = previousRank;
        this.currentRank = currentRank;
        this.trackDate = trackDate;
    }

    public Alertsdata(Integer resellerId, String campaign, String url, String keyword, String engine, int previousRank, int currentRank, Date trackDate) {
        this.resellerId = resellerId;
        this.campaign = campaign;
        this.url = url;
        this.keyword = keyword;
        this.engine = engine;
        this.previousRank = previousRank;
        this.currentRank = currentRank;
        this.trackDate = trackDate;
    }

    public Integer getAlertId() {
        return this.alertId;
    }

    public void setAlertId(Integer alertId) {
        this.alertId = alertId;
    }

    public Integer getResellerId() {
        return this.resellerId;
    }

    public void setResellerId(Integer resellerId) {
        this.resellerId = resellerId;
    }

    public String getCampaign() {
        return this.campaign;
    }

    public void setCampaign(String campaign) {
        this.campaign = campaign;
    }

    public String getUrl() {
        return this.url;
    }

    public void setUrl(String url) {
        this.url = url;
    }

    public String getKeyword() {
        return this.keyword;
    }

    public void setKeyword(String keyword) {
        this.keyword = keyword;
    }

    public String getEngine() {
        return this.engine;
    }

    public void setEngine(String engine) {
        this.engine = engine;
    }

    public int getPreviousRank() {
        return this.previousRank;
    }

    public void setPreviousRank(int previousRank) {
        this.previousRank = previousRank;
    }

    public int getCurrentRank() {
        return this.currentRank;
    }

    public void setCurrentRank(int currentRank) {
        this.currentRank = currentRank;
    }

    public Date getTrackDate() {
        return this.trackDate;
    }

    public void setTrackDate(Date trackDate) {
        this.trackDate = trackDate;
    }

    public Customers getCustomerID() {
        return customerID;
    }

    public void setCustomerID(Customers customerID) {
        this.customerID = customerID;
    }

    @XmlTransient
    public Collection<Reviewsite> getReviewsiteCollection() {
        return reviewsiteCollection;
    }

    public void setReviewsiteCollection(Collection<Reviewsite> reviewsiteCollection) {
        this.reviewsiteCollection = reviewsiteCollection;
    }

}
