package globuswoo.entity;
// Generated May 23, 2013 8:20:10 PM by Hibernate Tools 3.2.1.GA


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Monitor generated by hbm2java
 */
@Entity
@Table(name="monitor")
public class Monitor  implements java.io.Serializable {


     private Integer crawlId;
     private Integer startKeywordId;
     private Integer endKeywordId;
     private Date crawlInitTime;
     private Date crawlStartTime;
     private Date crawlEndTime;

    public Monitor() {
    }

    public Monitor(Integer startKeywordId, Integer endKeywordId, Date crawlInitTime, Date crawlStartTime, Date crawlEndTime) {
       this.startKeywordId = startKeywordId;
       this.endKeywordId = endKeywordId;
       this.crawlInitTime = crawlInitTime;
       this.crawlStartTime = crawlStartTime;
       this.crawlEndTime = crawlEndTime;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)
    
    @Column(name="CrawlID", unique=true, nullable=false)
    public Integer getCrawlId() {
        return this.crawlId;
    }
    
    public void setCrawlId(Integer crawlId) {
        this.crawlId = crawlId;
    }
    
    @Column(name="StartKeywordID")
    public Integer getStartKeywordId() {
        return this.startKeywordId;
    }
    
    public void setStartKeywordId(Integer startKeywordId) {
        this.startKeywordId = startKeywordId;
    }
    
    @Column(name="EndKeywordID")
    public Integer getEndKeywordId() {
        return this.endKeywordId;
    }
    
    public void setEndKeywordId(Integer endKeywordId) {
        this.endKeywordId = endKeywordId;
    }
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="CrawlInitTime", length=0)
    public Date getCrawlInitTime() {
        return this.crawlInitTime;
    }
    
    public void setCrawlInitTime(Date crawlInitTime) {
        this.crawlInitTime = crawlInitTime;
    }
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="CrawlStartTime", length=0)
    public Date getCrawlStartTime() {
        return this.crawlStartTime;
    }
    
    public void setCrawlStartTime(Date crawlStartTime) {
        this.crawlStartTime = crawlStartTime;
    }
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="CrawlEndTime", length=0)
    public Date getCrawlEndTime() {
        return this.crawlEndTime;
    }
    
    public void setCrawlEndTime(Date crawlEndTime) {
        this.crawlEndTime = crawlEndTime;
    }




}


