package globuswoo.entity;
// Generated May 23, 2013 8:20:10 PM by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Plans generated by hbm2java
 */
@Entity
@Table(name="plans")
public class Plans implements java.io.Serializable {


     private Integer planId;
     private String name;
     private int amount;
     private String currency;
     private int campaigns;
     private int keywords;
     private int users;
     private Set<Payments> paymentses = new HashSet<Payments>(0);

    public Plans() {
    }

	
    public Plans(String name, int amount, String currency, int campaigns, int keywords, int users) {
        this.name = name;
        this.amount = amount;
        this.currency = currency;
        this.campaigns = campaigns;
        this.keywords = keywords;
        this.users = users;
    }
    public Plans(String name, int amount, String currency, int campaigns, int keywords, int users, Set<Payments> paymentses) {
       this.name = name;
       this.amount = amount;
       this.currency = currency;
       this.campaigns = campaigns;
       this.keywords = keywords;
       this.users = users;
       this.paymentses = paymentses;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)
    
    @Column(name="PlanID", unique=true, nullable=false)
    public Integer getPlanId() {
        return this.planId;
    }
    
    public void setPlanId(Integer planId) {
        this.planId = planId;
    }
    
    @Column(name="Name", nullable=false, length=30)
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    
    @Column(name="Amount", nullable=false)
    public int getAmount() {
        return this.amount;
    }
    
    public void setAmount(int amount) {
        this.amount = amount;
    }
    
    @Column(name="Currency", nullable=false, length=5)
    public String getCurrency() {
        return this.currency;
    }
    
    public void setCurrency(String currency) {
        this.currency = currency;
    }
    
    @Column(name="Campaigns", nullable=false)
    public int getCampaigns() {
        return this.campaigns;
    }
    
    public void setCampaigns(int campaigns) {
        this.campaigns = campaigns;
    }
    
    @Column(name="Keywords", nullable=false)
    public int getKeywords() {
        return this.keywords;
    }
    
    public void setKeywords(int keywords) {
        this.keywords = keywords;
    }
    
    @Column(name="Users", nullable=false)
    public int getUsers() {
        return this.users;
    }
    
    public void setUsers(int users) {
        this.users = users;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="plans")
    public Set<Payments> getPaymentses() {
        return this.paymentses;
    }
    
    public void setPaymentses(Set<Payments> paymentses) {
        this.paymentses = paymentses;
    }




}


