package globuswoo.entity;
// Generated May 23, 2013 8:20:10 PM by Hibernate Tools 3.2.1.GA


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Reportfrequency generated by hbm2java
 */
@Entity
@Table(name="reportfrequency")
public class Reportfrequency  implements java.io.Serializable {


     private Integer frequencyId;
     private String frequencyDetail;

    public Reportfrequency() {
    }

    public Reportfrequency(String frequencyDetail) {
       this.frequencyDetail = frequencyDetail;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)
    
    @Column(name="FrequencyId", unique=true, nullable=false)
    public Integer getFrequencyId() {
        return this.frequencyId;
    }
    
    public void setFrequencyId(Integer frequencyId) {
        this.frequencyId = frequencyId;
    }
    
    @Column(name="FrequencyDetail", nullable=false, length=30)
    public String getFrequencyDetail() {
        return this.frequencyDetail;
    }
    
    public void setFrequencyDetail(String frequencyDetail) {
        this.frequencyDetail = frequencyDetail;
    }




}


