package globuswoo.entity;
// Generated May 23, 2013 8:20:10 PM by Hibernate Tools 3.2.1.GA


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Trackhistory generated by hbm2java
 */
@Entity
@Table(name="trackhistory")
public class Trackhistory  implements java.io.Serializable {


     private Integer trackId;
     private Date trackDate;
     private int keywordId;
     private Integer rankGoogle;
     private Integer bestMatchRankGoogle;
     private String bestMatchLinkGoogle;
     private Integer rankBing;
     private Integer bestMatchRankBing;
     private String bestMatchLinkBing;
     private Integer rankYahoo;
     private Integer bestMatchRankYahoo;
     private String bestMatchLinkYahoo;
     private Integer rankPage;
     private Integer rankAlexa;
     private Integer countBackLinks;
     private Integer countMonthlySearches;
     private Integer facebookLike;
     private Integer facebookShare;
     private Integer tweetCount;
     private Integer pinterestPins;
     private Integer googlePlusLikes;
     private Integer linkedInShares;
     private Integer redittVotes;
     private Integer stumbleUponLikes;

    public Trackhistory() {
    }

	
    public Trackhistory(int keywordId) {
        this.keywordId = keywordId;
    }
    public Trackhistory(Date trackDate, int keywordId, Integer rankGoogle, Integer bestMatchRankGoogle, String bestMatchLinkGoogle, Integer rankBing, Integer bestMatchRankBing, String bestMatchLinkBing, Integer rankYahoo, Integer bestMatchRankYahoo, String bestMatchLinkYahoo, Integer rankPage, Integer rankAlexa, Integer countBackLinks, Integer countMonthlySearches, Integer facebookLike, Integer facebookShare, Integer tweetCount, Integer pinterestPins, Integer googlePlusLikes, Integer linkedInShares, Integer redittVotes, Integer stumbleUponLikes) {
       this.trackDate = trackDate;
       this.keywordId = keywordId;
       this.rankGoogle = rankGoogle;
       this.bestMatchRankGoogle = bestMatchRankGoogle;
       this.bestMatchLinkGoogle = bestMatchLinkGoogle;
       this.rankBing = rankBing;
       this.bestMatchRankBing = bestMatchRankBing;
       this.bestMatchLinkBing = bestMatchLinkBing;
       this.rankYahoo = rankYahoo;
       this.bestMatchRankYahoo = bestMatchRankYahoo;
       this.bestMatchLinkYahoo = bestMatchLinkYahoo;
       this.rankPage = rankPage;
       this.rankAlexa = rankAlexa;
       this.countBackLinks = countBackLinks;
       this.countMonthlySearches = countMonthlySearches;
       this.facebookLike = facebookLike;
       this.facebookShare = facebookShare;
       this.tweetCount = tweetCount;
       this.pinterestPins = pinterestPins;
       this.googlePlusLikes = googlePlusLikes;
       this.linkedInShares = linkedInShares;
       this.redittVotes = redittVotes;
       this.stumbleUponLikes = stumbleUponLikes;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)
    
    @Column(name="TrackID", unique=true, nullable=false)
    public Integer getTrackId() {
        return this.trackId;
    }
    
    public void setTrackId(Integer trackId) {
        this.trackId = trackId;
    }
    @Temporal(TemporalType.DATE)
    @Column(name="TrackDate", length=0)
    public Date getTrackDate() {
        return this.trackDate;
    }
    
    public void setTrackDate(Date trackDate) {
        this.trackDate = trackDate;
    }
    
    @Column(name="KeywordID", nullable=false)
    public int getKeywordId() {
        return this.keywordId;
    }
    
    public void setKeywordId(int keywordId) {
        this.keywordId = keywordId;
    }
    
    @Column(name="RankGoogle")
    public Integer getRankGoogle() {
        return this.rankGoogle;
    }
    
    public void setRankGoogle(Integer rankGoogle) {
        this.rankGoogle = rankGoogle;
    }
    
    @Column(name="BestMatchRankGoogle")
    public Integer getBestMatchRankGoogle() {
        return this.bestMatchRankGoogle;
    }
    
    public void setBestMatchRankGoogle(Integer bestMatchRankGoogle) {
        this.bestMatchRankGoogle = bestMatchRankGoogle;
    }
    
    @Column(name="BestMatchLinkGoogle", length=300)
    public String getBestMatchLinkGoogle() {
        return this.bestMatchLinkGoogle;
    }
    
    public void setBestMatchLinkGoogle(String bestMatchLinkGoogle) {
        this.bestMatchLinkGoogle = bestMatchLinkGoogle;
    }
    
    @Column(name="RankBing")
    public Integer getRankBing() {
        return this.rankBing;
    }
    
    public void setRankBing(Integer rankBing) {
        this.rankBing = rankBing;
    }
    
    @Column(name="BestMatchRankBing")
    public Integer getBestMatchRankBing() {
        return this.bestMatchRankBing;
    }
    
    public void setBestMatchRankBing(Integer bestMatchRankBing) {
        this.bestMatchRankBing = bestMatchRankBing;
    }
    
    @Column(name="BestMatchLinkBing", length=300)
    public String getBestMatchLinkBing() {
        return this.bestMatchLinkBing;
    }
    
    public void setBestMatchLinkBing(String bestMatchLinkBing) {
        this.bestMatchLinkBing = bestMatchLinkBing;
    }
    
    @Column(name="RankYahoo")
    public Integer getRankYahoo() {
        return this.rankYahoo;
    }
    
    public void setRankYahoo(Integer rankYahoo) {
        this.rankYahoo = rankYahoo;
    }
    
    @Column(name="BestMatchRankYahoo")
    public Integer getBestMatchRankYahoo() {
        return this.bestMatchRankYahoo;
    }
    
    public void setBestMatchRankYahoo(Integer bestMatchRankYahoo) {
        this.bestMatchRankYahoo = bestMatchRankYahoo;
    }
    
    @Column(name="BestMatchLinkYahoo", length=300)
    public String getBestMatchLinkYahoo() {
        return this.bestMatchLinkYahoo;
    }
    
    public void setBestMatchLinkYahoo(String bestMatchLinkYahoo) {
        this.bestMatchLinkYahoo = bestMatchLinkYahoo;
    }
    
    @Column(name="RankPage")
    public Integer getRankPage() {
        return this.rankPage;
    }
    
    public void setRankPage(Integer rankPage) {
        this.rankPage = rankPage;
    }
    
    @Column(name="RankAlexa")
    public Integer getRankAlexa() {
        return this.rankAlexa;
    }
    
    public void setRankAlexa(Integer rankAlexa) {
        this.rankAlexa = rankAlexa;
    }
    
    @Column(name="CountBackLinks")
    public Integer getCountBackLinks() {
        return this.countBackLinks;
    }
    
    public void setCountBackLinks(Integer countBackLinks) {
        this.countBackLinks = countBackLinks;
    }
    
    @Column(name="CountMonthlySearches")
    public Integer getCountMonthlySearches() {
        return this.countMonthlySearches;
    }
    
    public void setCountMonthlySearches(Integer countMonthlySearches) {
        this.countMonthlySearches = countMonthlySearches;
    }
    
    @Column(name="FacebookLike")
    public Integer getFacebookLike() {
        return this.facebookLike;
    }
    
    public void setFacebookLike(Integer facebookLike) {
        this.facebookLike = facebookLike;
    }
    
    @Column(name="FacebookShare")
    public Integer getFacebookShare() {
        return this.facebookShare;
    }
    
    public void setFacebookShare(Integer facebookShare) {
        this.facebookShare = facebookShare;
    }
    
    @Column(name="TweetCount")
    public Integer getTweetCount() {
        return this.tweetCount;
    }
    
    public void setTweetCount(Integer tweetCount) {
        this.tweetCount = tweetCount;
    }
    
    @Column(name="PinterestPins")
    public Integer getPinterestPins() {
        return this.pinterestPins;
    }
    
    public void setPinterestPins(Integer pinterestPins) {
        this.pinterestPins = pinterestPins;
    }
    
    @Column(name="GooglePlusLikes")
    public Integer getGooglePlusLikes() {
        return this.googlePlusLikes;
    }
    
    public void setGooglePlusLikes(Integer googlePlusLikes) {
        this.googlePlusLikes = googlePlusLikes;
    }
    
    @Column(name="LinkedInShares")
    public Integer getLinkedInShares() {
        return this.linkedInShares;
    }
    
    public void setLinkedInShares(Integer linkedInShares) {
        this.linkedInShares = linkedInShares;
    }
    
    @Column(name="RedittVotes")
    public Integer getRedittVotes() {
        return this.redittVotes;
    }
    
    public void setRedittVotes(Integer redittVotes) {
        this.redittVotes = redittVotes;
    }
    
    @Column(name="StumbleUponLikes")
    public Integer getStumbleUponLikes() {
        return this.stumbleUponLikes;
    }
    
    public void setStumbleUponLikes(Integer stumbleUponLikes) {
        this.stumbleUponLikes = stumbleUponLikes;
    }




}


