package globuswoo.entity;
// Generated May 23, 2013 8:20:10 PM by Hibernate Tools 3.2.1.GA

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Users generated by hbm2java
 */
@Entity
@Table(name = "users")
public class Users implements java.io.Serializable {

    @Column(name = "Addeddate")
    @Temporal(TemporalType.TIMESTAMP)
    private Date addeddate;
    @Id
    @GeneratedValue(strategy = IDENTITY)
    @Column(name = "UserID", unique = true, nullable = false)
    private Integer userId;
    @ManyToOne(fetch = FetchType.EAGER)
    @JoinColumn(name = "CustomerID", nullable = false)
    private Customers customers;
    @Column(name = "ResellerId")
    private Integer resellerId;
    @Column(name = "LoginID", nullable = false, length = 50)
    private String loginId;
    @Column(name = "Password", nullable = false, length = 15)
    private String password;
    @Column(name = "UserType")
    private Integer userType;

    public Users() {
    }

    public Users(Customers customers, String loginId, String password) {
        this.customers = customers;
        this.loginId = loginId;
        this.password = password;
    }

    public Users(Customers customers, Integer resellerId, String loginId, String password, Integer userType) {
        this.customers = customers;
        this.resellerId = resellerId;
        this.loginId = loginId;
        this.password = password;
        this.userType = userType;
    }

    public Integer getUserId() {
        return this.userId;
    }

    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    public Customers getCustomers() {
        return this.customers;
    }

    public void setCustomers(Customers customers) {
        this.customers = customers;
    }

    public Integer getResellerId() {
        return this.resellerId;
    }

    public void setResellerId(Integer resellerId) {
        this.resellerId = resellerId;
    }

    public String getLoginId() {
        return this.loginId;
    }

    public void setLoginId(String loginId) {
        this.loginId = loginId;
    }

    public String getPassword() {
        return this.password;
    }

    public void setPassword(String password) {
        this.password = password;
    }

    public Integer getUserType() {
        return this.userType;
    }

    public void setUserType(Integer userType) {
        this.userType = userType;
    }

    public Date getAddeddate() {
        return addeddate;
    }

    public void setAddeddate(Date addeddate) {
        this.addeddate = addeddate;
    }
}
