package ranktracker.entity;
// Generated Oct 10, 2012 12:11:15 PM by Hibernate Tools 3.2.1.GA

import org.apache.log4j.Logger;

/**
 * MasterEmail generated by hbm2java
 */
public class MasterEmail implements java.io.Serializable {

    static Logger l = Logger.getLogger(MasterEmail.class.getName());
    private Integer id;
    private String emailAccount;
    private String password;
    private String smtpMailHost;
    private int smtpPort;
    private String mailSenderAlias;
    private String loginUrl;
    private String signature;
    private String mailSenderName;
    private String bcc;

    /**
     *
     */
    public MasterEmail() {
    }

    /**
     *
     * @param emailAccount
     * @param password
     * @param smtpMailHost
     * @param smtpPort
     * @param mailSenderAlias
     * @param loginUrl
     * @param signature
     * @param mailSenderName
     */
    public MasterEmail(String emailAccount, String password, String smtpMailHost, int smtpPort, String mailSenderAlias, String loginUrl, String signature, String mailSenderName) {
        this.emailAccount = emailAccount;
        this.password = password;
        this.smtpMailHost = smtpMailHost;
        this.smtpPort = smtpPort;
        this.mailSenderAlias = mailSenderAlias;
        this.loginUrl = loginUrl;
        this.signature = signature;
        this.mailSenderName = mailSenderName;
    }

    /**
     *
     * @param emailAccount
     * @param password
     * @param smtpMailHost
     * @param smtpPort
     * @param mailSenderAlias
     * @param loginUrl
     * @param signature
     * @param mailSenderName
     * @param bcc
     */
    public MasterEmail(String emailAccount, String password, String smtpMailHost, int smtpPort, String mailSenderAlias, String loginUrl, String signature, String mailSenderName, String bcc) {
        this.emailAccount = emailAccount;
        this.password = password;
        this.smtpMailHost = smtpMailHost;
        this.smtpPort = smtpPort;
        this.mailSenderAlias = mailSenderAlias;
        this.loginUrl = loginUrl;
        this.signature = signature;
        this.mailSenderName = mailSenderName;
        this.bcc = bcc;
    }

    /**
     *
     * @return
     */
    public Integer getId() {
        return this.id;
    }

    /**
     *
     * @param id
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     *
     * @return
     */
    public String getEmailAccount() {
        return this.emailAccount;
    }

    /**
     *
     * @param emailAccount
     */
    public void setEmailAccount(String emailAccount) {
        this.emailAccount = emailAccount;
    }

    /**
     *
     * @return
     */
    public String getPassword() {
        return this.password;
    }

    /**
     *
     * @param password
     */
    public void setPassword(String password) {
        this.password = password;
    }

    /**
     *
     * @return
     */
    public String getSmtpMailHost() {
        return this.smtpMailHost;
    }

    /**
     *
     * @param smtpMailHost
     */
    public void setSmtpMailHost(String smtpMailHost) {
        this.smtpMailHost = smtpMailHost;
    }

    /**
     *
     * @return
     */
    public int getSmtpPort() {
        return this.smtpPort;
    }

    /**
     *
     * @param smtpPort
     */
    public void setSmtpPort(int smtpPort) {
        this.smtpPort = smtpPort;
    }

    /**
     *
     * @return
     */
    public String getMailSenderAlias() {
        return this.mailSenderAlias;
    }

    /**
     *
     * @param mailSenderAlias
     */
    public void setMailSenderAlias(String mailSenderAlias) {
        this.mailSenderAlias = mailSenderAlias;
    }

    /**
     *
     * @return
     */
    public String getLoginUrl() {
        return this.loginUrl;
    }

    /**
     *
     * @param loginUrl
     */
    public void setLoginUrl(String loginUrl) {
        this.loginUrl = loginUrl;
    }

    /**
     *
     * @return
     */
    public String getSignature() {
        return this.signature;
    }

    /**
     *
     * @param signature
     */
    public void setSignature(String signature) {
        this.signature = signature;
    }

    /**
     *
     * @return
     */
    public String getMailSenderName() {
        return this.mailSenderName;
    }

    /**
     *
     * @param mailSenderName
     */
    public void setMailSenderName(String mailSenderName) {
        this.mailSenderName = mailSenderName;
    }

    /**
     *
     * @return
     */
    public String getBcc() {
        return this.bcc;
    }

    /**
     *
     * @param bcc
     */
    public void setBcc(String bcc) {
        this.bcc = bcc;
    }
}
